### ISSUE TITLE
Whiteboard

### ISSUE THREAD

**Issue by ZanButt** [opencoca/Latitude#46]
The whiteboard in two of the classrooms don't seem to be working. With the first being the Mixart studios : production musicale - Boris P room and the second being the Guitare & Ukulélé - Alexandre Bernier room.

**Comment by shadowlerone** [comment]
Alright, I think I figured it out.
This may have to be a fix on the API level, as the rooms contain illegal characters.
I suspect the `:` and the `&` are causing the problems

**Comment by shadowlerone** [comment]
I changed the names on the API level and that seems to be the case.
Moving forwards, I think we may either have to:
setup rules regarding what room names we use (irk)
or
use the `meet` property instead of the `name` property.

**Comment by opencoca** [comment]
The simplest option is to use the use the '''meet''' property. It's meant unique and will never contain spaces.

**Comment by shadowlerone** [comment]
done!

**Comment by shadowlerone** [comment]
Although, I hope no one had anything critical in those whiteboards since those will be lost.
